"""students model changed

Revision ID: 3e67cd5043bd
Revises: d302d941afad
Create Date: 2020-09-01 15:23:09.120146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e67cd5043bd'
down_revision = 'd302d941afad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'user', ['user_id'], ['id'])
    op.drop_column('student', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('course_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'course', ['course_id'], ['id'])
    op.drop_column('student', 'user_id')
    # ### end Alembic commands ###
